;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!


;; Load user details generated by Nix
(load! "user-details.el" nil t)

;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-symbol-font' -- for symbols
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept. For example:
;;
;;(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
;;      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
;;
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!

;; Changed "Hack Nerd Font Mono" to "Hack Nerd Font" to ensure correct glyph rendering in GUI.
(setq doom-font (font-spec :family "Hack Nerd Font" :size 22)
      doom-variable-pitch-font (font-spec :family "FreeSans" :size 22)
      doom-big-font (font-spec :family "Hack Nerd Font" :size 40)
      doom-symbol-font (font-spec :family "Hack Nerd Font"))

;; Use Noto Color Emoji for Unicode symbols
(after! doom-themes
  (set-fontset-font t 'unicode (font-spec :family "Noto Color Emoji") nil 'prepend))

;; Hidden emphasis markers
(after! doom-themes
  (setq doom-themes-enable-italic t
        doom-themes-enable-bold t))
;; Italicized comments
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-dark+)

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
;; (setq org-directory "~/org/")


;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

;; Trocar logo
;; (setq fancy-splash-image "~/.doom.d/logo/emacs-e.svg")
(setq fancy-splash-image "~/.config/doom/logo/emacs-e.png")

;; Inicar maximizado
(add-to-list 'default-frame-alist '(fullscreen . maximized))

;; Habilitar auto-save
(setq auto-save-default t)

;; Input method is configured dynamically by Nix in user-details.el

;; Org mode
(add-hook 'org-mode-hook 'org-indent-mode)
;; Desabilitar número de linhas no org-mode
(add-hook 'org-mode-hook (lambda () (display-line-numbers-mode 0)))
;; Outras personalizações
(setq org-blank-before-new-entry '((heading . auto) (plain-list-item . auto))
      org-default-notes-file (expand-file-name "notes.org" org-directory)
      org-ellipsis " ▼ "
      org-log-done 'time
      org-journal-date-format "%B %d, %Y (%A) "
      org-journal-file-format "%Y-%m-%d.org"
      org-hide-emphasis-markers t
      org-superstar-headline-bullets-list '("⁖" "◉" "○" "✸" "✿")
      org-capture-templates
      '(("t" "Personal todo" entry
              (file+headline +org-capture-todo-file "Inbox")
         "* TODO %?\n%i\n%a" :prepend t)
        ("n" "Personal notes" entry
         (file+headline +org-capture-notes-file "Inbox")
         "* %u %?\n%i\n%a" :prepend t)
        ("j" "Journal" entry
         (file+olp+datetree +org-capture-journal-file)
         "* %U %?\n%i\n%a" :prepend t)

        ;; Will use {project-root}/{todo,notes,changelog}.org, unless a
        ;; {todo,notes,changelog}.org file is found in a parent directory.
        ;; Uses the basename from `+org-capture-todo-file',
        ;; `+org-capture-changelog-file' and `+org-capture-notes-file'.
        ("p" "Templates for projects")
        ("pt" "Project-local todo" entry  ; {project-root}/todo.org
         (file+headline +org-capture-project-todo-file "Inbox")
         "* TODO %?\n%i\n%a" :prepend t)
        ("pn" "Project-local notes" entry  ; {project-root}/notes.org
         (file+headline +org-capture-project-notes-file "Inbox")
         "* %U %?\n%i\n%a" :prepend t)
        ("pc" "Project-local changelog" entry  ; {project-root}/changelog.org
         (file+headline +org-capture-project-changelog-file "Unreleased")
         "* %U %?\n%i\n%a" :prepend t)

        ;; Will use {org-directory}/{+org-capture-projects-file} and store
        ;; these under {ProjectName}/{Tasks,Notes,Changelog} headings. They
        ;; support `:parents' to specify what headings to put them under, e.g.
        ;; :parents ("Projects")
        ("o" "Centralized templates for projects")
        ("ot" "Project todo" entry
         (function +org-capture-central-project-todo-file)
         "* TODO %?\n %i\n %a"
         :heading "Tasks"
         :prepend nil)
        ("on" "Project notes" entry
         (function +org-capture-central-project-notes-file)
         "* %U %?\n %i\n %a"
         :heading "Notes"
         :prepend t)
        ("oc" "Project changelog" entry
         (function +org-capture-central-project-changelog-file)
         "* %U %?\n %i\n %a"
         :heading "Changelog"
         :prepend t))
      )
(setq org-src-preserve-indentation nil
      org-src-tab-acts-natively t
      org-edit-src-content-indentation 0)

;; Itens diferentes para prioridades
(use-package! org-fancy-priorities
  :hook (org-mode . org-fancy-priorities-mode)
  :config (setq org-fancy-priorities-list '("⚡" "⬆" "⬇" "☕")))

;; Org para html
(require 'ox-html)

;; Numeração relativa de linhas
(setq display-line-numbers-type 'relative)

;; Evil Snipe buffer inteiro
(use-package! evil-snipe
  :config (setq evil-snipe-scope 'whole-buffer)
)

;; LSP UI and Doc configuration
(after! lsp-ui
  (setq lsp-ui-doc-enable t
        lsp-ui-doc-position 'at-point
        lsp-ui-doc-show-with-cursor t
        lsp-ui-doc-show-with-mouse nil))

;; Corfu popup documentation
(after! corfu
  (setq corfu-auto t
        corfu-auto-delay 0.2
        corfu-auto-prefix 2)
  (corfu-popupinfo-mode 1)
  (setq corfu-popupinfo-delay 0.5
        corfu-popupinfo-max-width 70
        corfu-popupinfo-max-height 20))

;; Enable Cape (Completion At Point Extensions) for better fallback completion
(after! cape
  (add-to-list 'completion-at-point-functions #'cape-dabbrev)
  (add-to-list 'completion-at-point-functions #'cape-file))

;; GPTel Configuration (Improved with Leader Menu & AI Completions)
(use-package! gptel
  :config
  (setq gptel-model 'deepseek-v4-flash
        gptel-backend (gptel-make-openai "DeepSeek"
                        :host "api.deepseek.com"
                        :endpoint "/chat/completions"
                        :stream t
                        :key (lambda ()
                               (with-temp-buffer
                                 (insert-file-contents "/run/secrets/deepseek_api_key")
                                 (string-trim (buffer-string))))
                        :models '(deepseek-v4-flash deepseek-v4-pro)))
  
  (defun +gptel-assist (beg end)
    "Prompt for an instruction and invoke gptel on the region."
    (interactive "r")
    (let ((prompt (read-string "AI Instruction: "))
          (context (if (use-region-p) (cons beg end) (cons (point-min) (point-max)))))
      (gptel-request
       prompt :context context :stream t :buffer (current-buffer)
       :position (if (use-region-p) end (point-max))
       :system "You are a coding assistant. Output ONLY the code, no markdown backticks.")))

  (defun +gptel/complete-at-point ()
    "AI-powered code completion (Ghost Text Style - Manual Trigger)."
    (interactive)
    (let ((gptel-model (if (derived-mode-p 'prog-mode) 'deepseek-v4-flash 'deepseek-v4-pro))
          (prefix (buffer-substring-no-properties (max (point-min) (- (point) 1500)) (point))))
      (gptel-request
       prefix
       :system "Complete the following code. Output ONLY the code to be appended. No markdown backticks."
       :callback (lambda (response info) (insert response)))))

  (map! :leader
        (:prefix-map ("c g" . "gpt")
         :desc "GPT Assist"     "a" #'+gptel-assist
         :desc "GPT Complete"   "c" #'+gptel/complete-at-point
         :desc "GPT Rewrite"    "r" #'gptel-rewrite
         :desc "GPT Menu"       "m" #'gptel-menu
         :desc "GPT Chat"       "g" #'gptel
         :desc "GPT Abort"      "k" #'gptel-abort)))

;; Native Ghost-Text preview for standard completions
(use-package! completion-preview
  :hook (prog-mode . completion-preview-mode)
  :config
  (setq completion-preview-minimum-symbol-length 2)
  (map! :map completion-preview-active-mode-map
        "TAB" #'completion-preview-insert
        "<tab>" #'completion-preview-insert))

;; Nix Highlighting & Tree-Sitter
(after! nix-mode
  (setq nix-indent-function 'nix-indent-line)
  (add-hook 'nix-mode-hook (lambda () 
                            (setq-local font-lock-extra-managed-props '(composition))
                            (setq-local lsp-semantic-tokens-enable nil)
                            (font-lock-flush))))

(if (modulep! :tools tree-sitter)
    (add-to-list 'major-mode-remap-alist '(nix-mode . nix-ts-mode)))

;; Python
;; (setq flycheck-python-pylint-executable "pylint")
;; (require 'lsp-python-ms)
;; (setq lsp-python-ms-auto-install-server t)
;; (add-hook 'python-mode-hook #'lsp) ; or lsp-deferred
;; (use-package! lsp-python-ms
;;   :ensure t
;;   :init (setq lsp-python-ms-auto-install-server t)
;;   :hook (python-mode . (lambda () 
;;                           (require 'lsp-python-ms)
;;                           (lsp))))  ; or lsp-deferred
;; (setq +python-ipython-repl-args '("-i" "--simple-prompt" "--no-color-info"))

;; Latex
(setq org-latex-create-formula-image-program 'dvipng)

;; ;; org-tree-slide config
;; (use-package! org-tree-slide
;;   :custom
;;   (org-image-actual-width nil))

;; evil-multiedit
(require 'evil-multiedit)
(evil-multiedit-default-keybinds)
;; Highlights all matches of the selection in the buffer.
(define-key evil-visual-state-map "R" 'evil-multiedit-match-all)

;; Match the word under cursor (i.e. make it an edit region). Consecutive presses will
;; incrementally add the next unmatched match.
(define-key evil-normal-state-map (kbd "M-d") 'evil-multiedit-match-and-next)
;; Match selected region.
(define-key evil-visual-state-map (kbd "M-d") 'evil-multiedit-match-and-next)
;; Insert marker at point
(define-key evil-insert-state-map (kbd "M-d") 'evil-multiedit-toggle-marker-here)

;; Same as M-d but in reverse.
(define-key evil-normal-state-map (kbd "M-D") 'evil-multiedit-match-and-prev)
(define-key evil-visual-state-map (kbd "M-D") 'evil-multiedit-match-and-prev)

;; OPTIONAL: If you prefer to grab symbols rather than words, use
;; `evil-multiedit-match-symbol-and-next` (or prev).

;; Restore the last group of multiedit regions.
(define-key evil-visual-state-map (kbd "C-M-D") 'evil-multiedit-restore)

;; RET will toggle the region under the cursor
;; (define-key evil-multiedit-state-map (kbd "RET") 'evil-multiedit-toggle-or-restrict-region)

;; ...and in visual mode, RET will disable all fields outside the selected region
(define-key evil-motion-state-map (kbd "RET") 'evil-multiedit-toggle-or-restrict-region)

;; For moving between edit regions
;; (define-key evil-multiedit-state-map (kbd "C-n") 'evil-multiedit-next)
;; (define-key evil-multiedit-state-map (kbd "C-p") 'evil-multiedit-prev)
;; (define-key evil-multiedit-insert-state-map (kbd "C-n") 'evil-multiedit-next)
;; (define-key evil-multiedit-insert-state-map (kbd "C-p") 'evil-multiedit-prev)

;; Ex command that allows you to invoke evil-multiedit with a regular expression, e.g.
(evil-ex-define-cmd "ie[dit]" 'evil-multiedit-ex-match)
