#!/bin/sh
# PT-BR: Inclui a configuração gerada pelo "p10k configure" manualmente,
# pois o zplug não pode editar o arquivo zshrc do home-manager.
# A configuração foi movida da sua localização original para /etc/nixos/p10k.
# EN-US: Manually include the configuration generated by "p10k configure",
# as zplug cannot edit home-manager's zshrc file.
# The configuration was moved from its original location to /etc/nixos/p10k.


## Keybindings section
bindkey -e
bindkey '^[[7~' beginning-of-line                               # Home key
bindkey '^[[H' beginning-of-line                                # Home key
if [[ "${terminfo[khome]}" != "" ]]; then
bindkey "${terminfo[khome]}" beginning-of-line                # [Home] - Go to beginning of line
fi
bindkey '^[[8~' end-of-line                                     # End key
bindkey '^[[F' end-of-line                                     # End key
if [[ "${terminfo[kend]}" != "" ]]; then
bindkey "${terminfo[kend]}" end-of-line                       # [End] - Go to end of line
fi
bindkey '^[[2~' overwrite-mode                                  # Insert key
bindkey '^[[3~' delete-char                                     # Delete key
bindkey '^[[C'  forward-char                                    # Right key
bindkey '^[[D'  backward-char                                   # Left key
bindkey '^[[5~' history-beginning-search-backward               # Page up key
bindkey '^[[6~' history-beginning-search-forward                # Page down key
# Navigate words with ctrl+arrow keys
bindkey '^[Oc' forward-word                                     #
bindkey '^[Od' backward-word                                    #
bindkey '^[[1;5D' backward-word                                 #
bindkey '^[[1;5C' forward-word                                  #
bindkey '^H' backward-kill-word                                 # delete previous word with ctrl+backspace
bindkey '^[[Z' undo                                             # Shift+tab undo last action
# Theming section
autoload -U colors
colors
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
# zsh custom functions
copy_stable () {
cp -r "$1" "${1}-stable-$(date +'%Y-%m-%d_%H%M')";
}

# Compare NixOS system generations using nvd
# Tries multiple strategies to find comparable system builds
nixdiff-latest () {
  local links valid_links=() link
  
  # Strategy 1: Find two most recent valid system generation links
  # Use nullglob to avoid literal pattern when no matches
  setopt local_options nullglob 2>/dev/null || true
  links=(/nix/var/nix/profiles/system-*-link(N))
  # Fallback if nullglob not available (zsh-specific)
  if [[ ${#links[@]} -eq 0 ]]; then
    links=($(ls -d1v /nix/var/nix/profiles/system-*-link 2>/dev/null))
  fi
  
  for link in "${links[@]}"; do
    # Check if symlink is valid (both symlink exists and target exists)
    if [[ -L "$link" ]] && [[ -e "$link" ]]; then
      valid_links+=("$link")
    fi
  done
  
  # If we have at least two valid generation links, compare the last two
  if [[ ${#valid_links[@]} -ge 2 ]]; then
    nvd diff "${valid_links[@]: -2}"
    return $?
  fi
  
  # Strategy 2: Compare current vs booted system (shows changes requiring reboot)
  if [[ -L "/run/current-system" ]] && [[ -e "/run/current-system" ]] && \
     [[ -L "/run/booted-system" ]] && [[ -e "/run/booted-system" ]]; then
    echo "Comparing current system vs booted system (shows changes requiring reboot):" >&2
    nvd diff /run/current-system /run/booted-system
    return $?
  fi
  
  # Strategy 3: Compare current system vs most recent available generation
  if [[ -L "/run/current-system" ]] && [[ -e "/run/current-system" ]] && \
     [[ ${#valid_links[@]} -ge 1 ]]; then
    echo "Comparing current system vs most recent available generation:" >&2
    nvd diff /run/current-system "${valid_links[-1]}"
    return $?
  fi
  
  # Strategy 4: Check if /nix/var/nix/profiles/system exists (current generation)
  if [[ -L "/nix/var/nix/profiles/system" ]] && [[ -e "/nix/var/nix/profiles/system" ]] && \
     [[ ${#valid_links[@]} -ge 1 ]]; then
    echo "Comparing current profile vs most recent available generation:" >&2
    nvd diff /nix/var/nix/profiles/system "${valid_links[-1]}"
    return $?
  fi
  
  # No viable comparison found
  echo "Error: Could not find comparable system generations" >&2
  echo "  Available paths:" >&2
  [[ -L "/run/current-system" ]] && echo "    /run/current-system (symlink)" >&2
  [[ -e "/run/current-system" ]] || echo "    /run/current-system target missing" >&2
  [[ -L "/run/booted-system" ]] && echo "    /run/booted-system (symlink)" >&2
  [[ -e "/run/booted-system" ]] || echo "    /run/booted-system target missing" >&2
  [[ -L "/nix/var/nix/profiles/system" ]] && echo "    /nix/var/nix/profiles/system (symlink)" >&2
  [[ -e "/nix/var/nix/profiles/system" ]] || echo "    /nix/var/nix/profiles/system target missing" >&2
  echo "    Valid generation links found: ${#valid_links[@]}" >&2
  [[ ${#links[@]} -gt 0 ]] && echo "    Total generation links found: ${#links[@]}" >&2
  return 1
}

# Print a colorized, categorized list of custom NixOS and shell aliases
myaliases () {
  printf "\n\033[1;36m=== Custom NixOS & Shell Aliases ===\033[0m\n\n"

  printf "\033[1;34m--- Navigation & Core ---\033[0m\n"
  printf "  \033[1;32mll\033[0m                -> \033[1;33mls -la --group-directories-first --color\033[0m \033[2m(List all files)\033[0m\n"
  printf "  \033[1;32ml\033[0m                 -> \033[1;33mls -l --group-directories-first --color\033[0m \033[2m(List files)\033[0m\n"
  printf "  \033[1;32mcl\033[0m                -> \033[1;33mclear\033[0m \033[2m(Clear terminal screen)\033[0m\n"
  printf "\n"

  printf "\033[1;34m--- NixOS & Flakes ---\033[0m\n"
  printf "  \033[1;32mnfu\033[0m               -> \033[1;33mnix flake update\033[0m \033[2m(Update flake inputs)\033[0m\n"
  printf "  \033[1;32mnrswitch\033[0m          -> \033[1;33msudo nixos-rebuild switch --flake path:.#nixos --max-jobs 1 --show-trace\033[0m \033[2m(Apply system configuration)\033[0m\n"
  printf "  \033[1;32mnrtest\033[0m            -> \033[1;33msudo nixos-rebuild test --flake path:.#nixos --max-jobs 1 --show-trace\033[0m \033[2m(Test system configuration)\033[0m\n"
  printf "  \033[1;32mhmswitch\033[0m          -> \033[1;33mhome-manager switch --flake path:.\033[0m \033[2m(Apply Home Manager configuration)\033[0m\n"
  printf "  \033[1;32mnixdiff\033[0m           -> \033[1;33mnixdiff-latest\033[0m \033[2m(Compare system build generations)\033[0m\n"
  printf "  \033[1;32mnrepl\033[0m             -> \033[1;33mnix repl --file '<nixpkgs>'\033[0m \033[2m(Nix REPL with nixpkgs)\033[0m\n"
  printf "\n"

  printf "\033[1;34m--- Cleanup & Optimization ---\033[0m\n"
  printf "  \033[1;32mnixstorecl\033[0m        -> \033[1;33m(Cleanup HM/System generations > 7 days & optimize store)\033[0m\n"
  printf "  \033[1;32mnixstorecl_active\033[0m -> \033[1;33m(Targeted cleanup: deletes ALL but current active generations)\033[0m\n"
  printf "  \033[1;32mhm-clean\033[0m          -> \033[1;33m(Expire Home Manager generations older than 7 days)\033[0m\n"
  printf "  \033[1;32mhm-clean_active\033[0m   -> \033[1;33m(Expire ALL Home Manager generations except current active)\033[0m\n"
  printf "  \033[1;32mgrubclean\033[0m         -> \033[1;33m(Clean system generations > 7d and update bootloader menu)\033[0m\n"
  printf "  \033[1;32mgrubclean_active\033[0m  -> \033[1;33m(Clean ALL system generations except current and update bootloader)\033[0m\n"
  printf "\n"

  printf "\033[1;34m--- Utility & Security ---\033[0m\n"
  printf "  \033[1;32mudb\033[0m               -> \033[1;33msudo updatedb\033[0m \033[2m(Update locate search database)\033[0m\n"
  printf "  \033[1;32mcsc\033[0m               -> \033[1;33mclamscan --recursive --infected ...\033[0m \033[2m(Scan directory with ClamAV)\033[0m\n"
  printf "  \033[1;32mfsize\033[0m             -> \033[1;33mdu -shc\033[0m \033[2m(Display disk space usage summary)\033[0m\n"
  printf "\n"
}
